/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectta;

import control.DocumenReader;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rizka-Nabillah
 */
public class Testing extends javax.swing.JFrame {

    /**
     * Creates new form Testing
     */
    private DefaultTableModel model_data, model_image_testing;
    private String path_foldder; // nyimpn alamat folder
    private ArrayList<String>  ListImageTesting = null; // nampung list image
    private DocumenReader dr = new DocumenReader();
    String text;
    
    public Testing() {
        initComponents();
        SetTableImageTesting();
        
        clickTableImage();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB_Testing = new javax.swing.JTable();
        BT_Classification = new javax.swing.JButton();
        L_Citra_Testing = new javax.swing.JLabel();
        L_BloodType = new javax.swing.JLabel();
        CB_Blood = new javax.swing.JComboBox<>();
        BT_Load = new javax.swing.JButton();
        bt_akurasi = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        L_Citra_Testing1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TB_Testing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Image Path", "Type"
            }
        ));
        jScrollPane1.setViewportView(TB_Testing);

        BT_Classification.setText("Classification");
        BT_Classification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ClassificationActionPerformed(evt);
            }
        });

        L_Citra_Testing.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        L_BloodType.setText("Blood Type :");

        CB_Blood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));
        CB_Blood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_BloodActionPerformed(evt);
            }
        });

        BT_Load.setText("Load");
        BT_Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_LoadActionPerformed(evt);
            }
        });

        bt_akurasi.setText("Akurasi");

        jTextField1.setText("jTextField1");

        L_Citra_Testing1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(L_BloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CB_Blood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BT_Load)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BT_Classification, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(bt_akurasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(L_Citra_Testing, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(L_Citra_Testing1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_BloodType)
                            .addComponent(CB_Blood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT_Load))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(L_Citra_Testing, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(L_Citra_Testing1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(BT_Classification, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_akurasi)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("File", jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Help", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CB_BloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_BloodActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CB_BloodActionPerformed

    private void BT_LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_LoadActionPerformed
        // TODO add your handling code here:
        text = CB_Blood.getSelectedItem().toString();
        System.out.println(text);
        System.out.println(path_foldder);
        PreviewTableImageTesting();
        
    }//GEN-LAST:event_BT_LoadActionPerformed

    private void BT_ClassificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ClassificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_ClassificationActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // untuk ngatur tabel nampil list file
    public void SetTableImageTesting (){
        model_image_testing = new DefaultTableModel();
        TB_Testing.setModel(model_image_testing);
        model_image_testing.addColumn("No"); // buat kolom
        model_image_testing.addColumn("Part");
        model_image_testing.addColumn("Type");
        // ngatur besar kolom table
        TB_Testing.setAutoResizeMode(TB_Testing.AUTO_RESIZE_OFF);
        TB_Testing.getColumnModel().getColumn(0).setPreferredWidth(50);
        TB_Testing.getColumnModel().getColumn(1).setPreferredWidth(325);
        TB_Testing.getColumnModel().getColumn(2).setPreferredWidth(100);
    }
    
     // manggil folder untk tampil di table
    public void PreviewTableImageTesting (){
        ListImageTesting = new ArrayList<>(); // nampung nilai yg dkembalikan fungsi
        path_foldder = "E:\\UNSRI\\try\\WARUNG BELAJAR\\ProjectTA\\fileTA\\dataset\\data dipakai UJI\\" + text;
        
        File folder = new File(path_foldder);
        ListImageTesting = dr.ListFileForForlder(folder);
        for (int i=0; i<ListImageTesting.size(); i++){
            Object[] obj = new Object[3];
            obj [0] = (i+1);
            obj [1] = ListImageTesting.get(i);
            obj [2] = ListImageTesting.get(i).charAt(0);
            model_image_testing.addRow(obj);
            
        }
         // untk nampilkan gambar pertama kali
        String init_image = path_foldder + "\\" + ListImageTesting.get(0);
        ImageIcon img = dr.dataFromImage(init_image, L_Citra_Testing.getWidth(), L_Citra_Testing.getHeight());
        L_Citra_Testing.setIcon(img);
    }
    
    // method untk gambar berjalan berubah2
    private void clickTableImage (){
        TB_Testing.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent me){ // biar di click berubah
                int row = TB_Testing.rowAtPoint(me.getPoint());
                int col = TB_Testing.columnAtPoint(me.getPoint());
                if (row>=0 && col == 1 ){
                    String image_path = path_foldder + "\\" + ListImageTesting.get(row);
                    ImageIcon img = dr.dataFromImage(image_path, L_Citra_Testing.getWidth(), L_Citra_Testing.getHeight()); // nampung image ny
                    L_Citra_Testing.setIcon(img);
                }  
            }
        });
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Testing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Classification;
    private javax.swing.JButton BT_Load;
    private javax.swing.JComboBox<String> CB_Blood;
    private javax.swing.JLabel L_BloodType;
    private javax.swing.JLabel L_Citra_Testing;
    private javax.swing.JLabel L_Citra_Testing1;
    private javax.swing.JTable TB_Testing;
    private javax.swing.JButton bt_akurasi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
